import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {generateKeyPair,SignJWT} from 'jose';
import {OWNER,startLogin,googleLogin,getSession,changeUser,listUsers,verifyGoogle} from './auth.mjs';
import worker from './worker.mjs';
function environment(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));return {GOOGLE_CLIENT_ID:'test-client',DB:{prepare(sql){return {bind(...params){return {async first(){return db.prepare(sql).get(...params)||null},async all(){return {results:db.prepare(sql).all(...params)}},async run(){return {meta:db.prepare(sql).run(...params)}}}},async all(){return {results:db.prepare(sql).all()}},async first(){return db.prepare(sql).get()||null}}},async batch(items){db.exec('BEGIN');try{const result=await Promise.all(items.map(i=>i.run()));db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}},db};}
const request=cookie=>new Request('https://api.haodao.org/api/session',{headers:{Cookie:cookie||'',Origin:'https://www.haodao.org'}});
async function signIn(env,email,sub=email){const start=await startLogin(request(),env);return googleLogin(request(start.cookie),env,{credential:'test'},async()=>({email,sub}));}
test('owner login, allowlist, removal revokes sessions, protected owner',async()=>{const env=environment(),owner=await signIn(env,OWNER);assert.equal(owner.data.user.role,'owner');const current=await getSession(request(owner.cookie),env);assert.equal(current.email,OWNER);await changeUser(env,current,{action:'add',email:'Editor@gmail.com'});const editor=await signIn(env,'editor@gmail.com');assert.equal((await getSession(request(editor.cookie),env)).role,'editor');await assert.rejects(changeUser(env,editor.data.user,{action:'add',email:'evil@gmail.com'}),{status:403});await assert.rejects(listUsers(env,editor.data.user),{status:403});await assert.rejects(changeUser(env,current,{action:'remove',email:OWNER}),{status:403});await changeUser(env,current,{action:'remove',email:'editor@gmail.com'});assert.equal(await getSession(request(editor.cookie),env),null);await assert.rejects(signIn(env,'editor@gmail.com'),{status:403});assert.throws(()=>env.db.exec("DELETE FROM admin_users WHERE role='owner'"));});
test('unknown identity, changed Google identity, challenge replay and legacy sessions fail closed',async()=>{const env=environment();await assert.rejects(signIn(env,'unknown@gmail.com'),{status:403});await signIn(env,OWNER,'stable-sub');await assert.rejects(signIn(env,OWNER,'different-sub'),{status:403});const start=await startLogin(request(),env);await googleLogin(request(start.cookie),env,{credential:'x'},async()=>({email:OWNER,sub:'stable-sub'}));await assert.rejects(googleLogin(request(start.cookie),env,{credential:'x'},async()=>({email:OWNER,sub:'stable-sub'})),{status:401});assert.equal(await getSession(request('__Host-haodao_session='+'a'.repeat(64)),env),null);});
test('JWT validates Google signature, audience, expiry, nonce, verified and authoritative email',async()=>{const {privateKey,publicKey}=await generateKeyPair('RS256');const base={email:OWNER,email_verified:true,hd:'haodao.org',nonce:'nonce'};async function token(payload={},aud='client',exp='5m',key=privateKey){return new SignJWT({...base,...payload}).setProtectedHeader({alg:'RS256'}).setIssuer('https://accounts.google.com').setSubject('123').setAudience(aud).setIssuedAt().setExpirationTime(exp).sign(key)}assert.equal((await verifyGoogle(await token(),'client','nonce',publicKey)).email,OWNER);for(const value of [await token({},'wrong'),await token({},'client','-1s'),await token({nonce:'wrong'}),await token({email_verified:false}),await token({hd:undefined}),await token({},'client','5m',(await generateKeyPair('RS256')).privateKey)])await assert.rejects(verifyGoogle(value,'client','nonce',publicKey));});
test('API denies password bypass, hostile origins, missing CSRF and editor user-management',async()=>{const env=environment();const owner=await signIn(env,OWNER);const post=(path,body={},cookie=owner.cookie,csrf='',origin='https://www.haodao.org')=>worker.fetch(new Request('https://api.haodao.org/api/'+path,{method:'POST',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body)}),env,{});assert.equal((await post('login',{password:'old'})).status,410);assert.equal((await post('admin/users',{action:'add',email:'x@gmail.com'})).status,403);assert.equal((await post('auth/start',{},'','','https://evil.test')).status,403);assert.equal((await post('admin/users',{action:'add',email:'x@gmail.com'},owner.cookie,owner.data.csrf)).status,200);const editor=await signIn(env,'x@gmail.com');assert.equal((await post('admin/users',{action:'remove',email:OWNER},editor.cookie,editor.data.csrf)).status,403);});

test('course events ignore regions while community events require a region',async()=>{
 const env=environment(),owner=await signIn(env,OWNER);
 const base={title:'Test activity',kind:'courses',start_date:'2026-10-24',end_date:'2026-10-24',mode:'線上',region:'北區',description:'Test description'};
 const save=body=>worker.fetch(new Request('https://api.haodao.org/api/events',{method:'POST',headers:{Origin:'https://www.haodao.org',Cookie:owner.cookie,'Content-Type':'application/json','X-CSRF-Token':owner.data.csrf},body:JSON.stringify(body)}),env,{});
 const course=await save(base);assert.equal(course.status,200);assert.equal((await course.json()).event.region,'');
 assert.equal((await save({...base,kind:'community',region:''})).status,400);
 const community=await save({...base,kind:'community'});assert.equal(community.status,200);assert.equal((await community.json()).event.region,'北區');
});
